### ISSUE TITLE
Non-free data or data with obscure licenses

### ISSUE THREAD

**Issue by 375gnu** [CelestiaProject/CelestiaContent#1]
Some data files in Celestia has non-free, unknown or obscure licences. They should be replaced with free alternatives or their owner are asked to relicense them.

## Models
- [ ] models/geographos.3ds
- [ ] models/geographos.cmod
- [ ] models/kleopatra.3ds
- [ ] models/marsglobalsurvr.3ds
- [ ] models/marsodyssey.3ds
- [ ] models/toutatis.3ds
- [ ] models/toutatis.cmod

### Low Resolution
- [ ] textures/lores/amalthea.jpg
- [ ] textures/lores/ariel.jpg
- [ ] textures/lores/ariel-lok-mask.png
- [ ] textures/lores/callisto.jpg
- [ ] textures/lores/callisto-lok-mask.png
- [ ] textures/lores/charon-lok.jpg
- [ ] textures/lores/charon-lok-spec.jpg
- [x] textures/lores/deimos.jpg
- [ ] textures/lores/dione.jpg
- [ ] textures/lores/epimetheus.jpg
- [ ] textures/lores/epimetheus-lok.jpg
- [ ] textures/lores/eros.jpg
- [ ] textures/lores/europa.jpg
- [ ] textures/lores/europa-lok-mask.png
- [ ] textures/lores/ganymede.jpg
- [ ] textures/lores/ganymede-lok-mask.png
- [ ] textures/lores/gaspramosaic.jpg
- [ ] textures/lores/hyperion.jpg
- [ ] textures/lores/hyperion-lok.jpg
- [ ] textures/lores/iapetus.jpg
- [ ] textures/lores/idamosaic.jpg
- [ ] textures/lores/io.jpg
- [ ] textures/lores/io-lok-mask.png
- [ ] textures/lores/janus.jpg
- [x] textures/lores/jupiter.jpg
- [ ] textures/lores/marsbump.jpg
- [ ] textures/lores/mars.jpg
- [ ] textures/lores/mercury.jpg
- [ ] textures/lores/mimas.jpg
- [ ] textures/lores/miranda.jpg
- [ ] textures/lores/miranda-lok-mask.png
- [ ] textures/lores/moonbump.jpg
- [ ] textures/lores/moon.jpg
- [ ] textures/lores/neptune.jpg
- [ ] textures/lores/oberon.jpg
- [ ] textures/lores/oberon-lok-mask.png
- [x] textures/lores/phobos.jpg
- [ ] textures/lores/phoebe.jpg
- [ ] textures/lores/pluto-lok.jpg
- [ ] textures/lores/pluto-lok-spec.jpg
- [ ] textures/lores/prometheus.jpg
- [ ] textures/lores/proteus.jpg
- [ ] textures/lores/rhea.jpg
- [ ] textures/lores/tethys.jpg
- [ ] textures/lores/titan-clouds.jpg
- [ ] textures/lores/titania.jpg
- [ ] textures/lores/titania-lok-mask.png
- [ ] textures/lores/titan.jpg
- [ ] textures/lores/triton.jpg
- [ ] textures/lores/triton-lok-mask.png
- [ ] textures/lores/umbriel.jpg
- [ ] textures/lores/umbriel-lok-mask.png
- [ ] textures/lores/uranus.jpg
- [ ] textures/lores/uranus-rings.png
### Medium Resolution
- [ ] textures/medres/amalthea.jpg
- [ ] textures/medres/ariel.jpg
- [ ] textures/medres/callisto.jpg
- [ ] textures/medres/charon-lok.jpg
- [ ] textures/medres/charon-lok-spec.jpg
- [x] textures/medres/deimos.jpg
- [ ] textures/medres/dione.jpg
- [ ] textures/medres/epimetheus.jpg
- [ ] textures/medres/epimetheus-lok.jpg
- [ ] textures/medres/eros.jpg
- [ ] textures/medres/europa.jpg
- [ ] textures/medres/ganymede.jpg
- [ ] textures/medres/gaspramosaic.jpg
- [ ] textures/medres/hyperion.jpg
- [ ] textures/medres/hyperion-lok.jpg
- [ ] textures/medres/iapetus.jpg
- [ ] textures/medres/idamosaic.jpg
- [ ] textures/medres/io.jpg
- [ ] textures/medres/janus.jpg
- [x] textures/medres/jupiter.jpg
- [ ] textures/medres/marsbump.jpg
- [ ] textures/medres/mars.jpg
- [ ] textures/medres/mercury.jpg
- [ ] textures/medres/mimas.jpg
- [ ] textures/medres/miranda.jpg
- [ ] textures/medres/moonbump.jpg
- [ ] textures/medres/moon.jpg
- [ ] textures/medres/neptune.jpg
- [ ] textures/medres/oberon.jpg
- [x] textures/medres/phobos.jpg
- [ ] textures/medres/phoebe.jpg
- [ ] textures/medres/pluto-lok.jpg
- [ ] textures/medres/pluto-lok-spec.jpg
- [ ] textures/medres/prometheus.jpg
- [ ] textures/medres/proteus.jpg
- [ ] textures/medres/rhea.jpg
- [ ] textures/medres/tethys.jpg
- [ ] textures/medres/titan-clouds.jpg
- [ ] textures/medres/titania.jpg
- [ ] textures/medres/titan.jpg
- [ ] textures/medres/triton.jpg
- [ ] textures/medres/umbriel.jpg
### High Resolution
- [ ] textures/hires/iapetus.jpg
- [ ] textures/hires/moonbump.jpg
- [ ] textures/hires/moon.jpg
- [ ] textures/hires/phoebe.jpg
- [ ] textures/hires/tethys.jpg
- [ ] textures/hires/titan.jpg

**Comment by SevenSpheres** [comment]
This was fixed in #34
