### ISSUE TITLE
Clarify copyright on assets textures

### ISSUE THREAD

**Issue by eloyesp** [CelestiaProject/CelestiaContent#11]
It seems that copyright of some assets are not clear enough for the Debian team so those [files][] are extracted to a different package [celestia-common-nonfree][] stating that:

    This package contains the data files for Celestia that have no DFSG compatible license or an unclear license.

I've been looking and there is no clear mention on the copyright of those files so may be a proper mention of the source and license terms could allow them to merge those packages. Also FSF distros (like trisquel) seems to be removing this package for that reason and there is people [missing this package][]. There are some research made by debian on the [bugtracker][].

Regards.

[files]: https://packages.ubuntu.com/xenial/all/celestia-common-nonfree/filelist
[celestia-common-nonfree]: https://packages.debian.org/jessie/celestia-common-nonfree
[missing this package]: https://listas.trisquel.info/pipermail/trisquel-usuarios/2019-May/030538.html
[bugtracker]: http://bugs.debian.org/174456

**Comment by SevenSpheres** [comment]
This was fixed in #34

**Comment by StefanBruens** [comment]
The README contains a lot of Copyright notices, but hardly any usage licenses.

Should the GPL COPYING file imply these files are (almost) all under the GPL-2.0?

If yes, can you add a short notice to the README, stating "All files are under the GPL-2.0, or another permissive license as stated below."?
