### ISSUE TITLE
Consensus dwarf planets and where to put all of them

### ISSUE THREAD

**Issue by JiliTheSpaceboy** [CelestiaProject/CelestiaContent#127]
Scientists generally recognize 9 dwarf planets: Pluto, Eris, Haumea, Makemake, **Gonggong**, **Quaoar**, **Sedna**, **Orcus**, and Ceres. Four of these are 'consensus dwarf planets'; not recognized by IAU as dwarf planets, but given that they are generally treated as such. Given that the IAU does not seem to actively maintain the list of dwarf planets, I think it's a good idea for us to just go ahead and change their class to 'dwarfplanet'.

Another issue that has been raised is what to do with the location of these. There are three ideas:
1. Move the consensus dwarf planets to dwarfplanets.ssc.
2. Move all dwarf planets to their respective location files, and delete dwarfplanets.ssc. (In order for Pluto to still be selected when pressing 9, outersys.ssc should be loaded before asteroids.ssc.)
3. Move all dwarf planets to solarsys.ssc, and delete dwarfplanets.ssc. (The dwarf planets will be placed below the main planets.)

**Comment by SevenSpheres** [comment]
> Move all dwarf planets to their respective location files, and delete dwarfplanets.ssc.

This is my preferred option, but there's the question of what to do with Pluto to ensure it's still selected by the 9 key. It could be put in solarsys.ssc (as was the case before the Celestia Origin team split out dwarfplanets.ssc), or outersys.ssc could be loaded before asteroids.ssc in celestia.cfg

**Comment by JiliTheSpaceboy** [comment]
I personally prefer either 1. (serious) or 3. (bc funny). 1. has the least change from where we are now, and helps keep individual files at more manageable sizes (not that I'm sure if this is an issue or not, but I know it gets confusing).

**Comment by Askaniy** [comment]
I vote for "1". What about their class... not sure, I have no objections to either option
