### ISSUE TITLE
'moon' vs 'minormoon': consistent classification scheme

### ISSUE THREAD

**Issue by JiliTheSpaceboy** [CelestiaProject/CelestiaContent#129]
After working in the trans-Neptunian space for a while I noticed the oddity of Haumea's Hi'iaka being classified as a 'moon' while Namaka is a 'minormoon'. It turned out that there is an inconsistency in how minormoon is defined - it seems that in solarsys.ssc, 'minormoon' is defined as objects smaller than ~Mimas, or around 200 km radius (and Proteus is a 'moon' instead of 'minormoon'), while there does not seem to be a solid criteria for minor planet moons. I think this topic is likely worth discussing.

It has been highlighted that a 'moon' should be either:
1. Large enough to be potentially round
2. Large relative to their primary.

I decided to come up with a list of criteria to address this, defining a 'moon' class object as object **which fulfills one of these two criteria**:
1. Radius is greater or equal to 200 km (around Mimas' radius)
2. Mass ratio with primary is greater than 1:25. 1:25 is the mass ratio at which Lagrange points destabilize, and thus serve as a non-arbitrary dividing line.
2.1 In absence of mass, radius ratio can be used instead, and satellites with radius ratio greater than 1:25^(1/3) ≈ 1:2.924 can be given the class 'moon'. The ratio equation assumes equal density between primary and secondary.

**Objects that qualify the second criteria may also be given the class of the primary object instead** as they can be considered double objects. This would, for example, cover Charon, Vanth, Ilmarë, and Hiisi and Paha.

EDIT 1 (2023-12-16 16:16 UTC): clarify that the criteria is meant to be used as an OR list, not AND.

**Comment by Askaniy** [comment]
That was CO topic too, so I asked Zemlyanin, here's translation:

> That is, our Moon is a `minormoon` in terms of mass, since its mass relates to the mass of the Earth as 1:81.3.
Ganymede is also a `minormoon`, because its mass is relative to the mass of Jupiter as ~1:12700.
Something is missing here... Perhaps it is necessary to fulfill not all the proposed criteria at the same time, but at least one of them.
But I support the general approach of determining the `minormoon`, through the relationship of characteristics with the main body.

**Comment by JiliTheSpaceboy** [comment]
> That was CO topic too, so I asked Zemlyanin, here's translation:
> 
> > That is, our Moon is a `minormoon` in terms of mass, since its mass relates to the mass of the Earth as 1:81.3.
> > Ganymede is also a `minormoon`, because its mass is relative to the mass of Jupiter as ~1:12700.
> > Something is missing here... Perhaps it is necessary to fulfill not all the proposed criteria at the same time, but at least one of them.
> > But I support the general approach of determining the `minormoon`, through the relationship of characteristics with the main body.

Wait oh I'm sorry, I didn't write in that the satellite only need to fulfill only one of these 'criteria' to become a 'moon'. It's meant to be OR, not AND. Though could you also ask them if they think the criteria 2 should make object get the same class as their parent (AKA last paragraph)?

**Comment by JiliTheSpaceboy** [comment]
Given that it's been a whole week I'm going ahead with this. I'm going to go with making moons that are large relative to their parent object as 'moon' for now.

**Comment by JiliTheSpaceboy** [comment]
UPDATE: I decided to modify the criteria slightly: now the 'relatively large' moons are given their physical class instead of just adopting their parent body's. This applies for Vanth, which is now an asteroid due to being large relative to its parent planet but not large enough to be a dwarf planet itself.

**Comment by SevenSpheres** [comment]
Slightly different criteria following my comment in #136:
- Satellites at least 200 km in radius use "moon" (their parent body is presumably "planet" or "dwarfplanet")
- Smaller satellites that have a mass ratio with their parent greater than 1:25 use the same class as their parent (presumably "asteroid"), same radius criterion can be used if mass is unknown
- Satellites that meet neither of the above criteria use "minormoon"
- Paha's parent body is the Lempo-Hiisi binary, not just Lempo
