### ISSUE TITLE
FarGetaNik star textures

### ISSUE THREAD

**Issue by ajtribick** [CelestiaProject/CelestiaContent#147]
Continuing with issues split out of #138

* astar.jpg<sup>1</sup>
* bstar.jpg<sup>1</sup>
* fstar.jpg<sup>1</sup>
* gstar.jpg<sup>1</sup>
* kstar.jpg<sup>1</sup>
* lstar.jpg<sup>1</sup>
* mstar.jpg<sup>2</sup>
* ostar.jpg<sup>1</sup>
* tstar.jpg<sup>3</sup>
* whitedwarf.jpg<sup>1,4</sup>

<sup>1</sup> - according to the README, derived from SDO images, see https://sdo.gsfc.nasa.gov/gallery/copyright/

<sup>2</sup> - according to README, derived from Swedish Solar Telescope images. According to https://ttt.astro.su.se/isf/gallery/ "Please credit the telescope and the Institute for Solar Physics as well as the observers for the individual images".

<sup>3</sup> - derived from a fictional texture by John Van Vliet.

<sup>4</sup> - grayscale version of astar.jpg

DeviantArt links:

* https://www.deviantart.com/fargetanik/art/Star-Texture-Map-2k-Spectral-Type-L-814586638 - lstar.jpg
* https://www.deviantart.com/fargetanik/art/Star-Texture-Map-4k-F-G-K-Spectral-Types-814379574 - fstar.jpg, gstar.jpg, kstar.jpg
* https://www.deviantart.com/fargetanik/art/Star-Texture-Map-4k-O-B-A-spectral-types-814254075 - ostar.jpg, bstar.jpg, astar.jpg
* https://www.deviantart.com/fargetanik/art/Star-Texture-Map-4k-Spectral-Type-M-814462913 - mstar.jpg

**Summary**

* With the exception of the tstar.jpg texture and the whitedwarf.jpg texture, the textures are available on FarGetaNik's DeviantArt page under the CC-BY-NC-SA-3.0 license. I am pretty sure that the "noncommercial" part of that is going to cause issues for packaging in various Linux distributions.
* Given the lack of knowledge of the precise sources used for the mstar.jpg texture, it is not clear to me that we can actually use this one and meet the requirements set on the Swedish Solar Telescope website.
* For tstar.jpg, we would need to find the John Van Vliet texture and confirm what the license is on that.

**Comment by JiliTheSpaceboy** [comment]
FarGetaNik told me that they intended to update the star textures once BlendTexture is implemented for stars, so I guess this is a good coincidence for us to review these textures.

**Comment by ajtribick** [comment]
We should also ask if we can use the textures under CC-BY or CC-BY-SA rather than CC-BY-NC-SA.

**Comment by ajtribick** [comment]
Per discussions on Discord, we should look at replacing these.

**Comment by ajtribick** [comment]
Tracking this under #193
