### ISSUE TITLE
Conflicting localization: Hydra (constellation) vs Hydra (moon of Pluto)

### ISSUE THREAD

**Issue by ajtribick** [CelestiaProject/CelestiaContent#189]
Currently Pluto's moon Hydra is localized as "The Water Serpent" due to the localization of the constellation Hydra. The .pot generator should probably add a "constellation" context to the constellation names to avoid this happening (plus make relevant changes in the Celestia codebase).

It might also be useful to use the full object paths to generate contexts for all objects in the translations, e.g. in case Atlas (star in the Pleiades) needs a different translation to Atlas (moon of Saturn).

**Comment by 375gnu** [comment]
Oh, this will break all translations. But if there is no other ways, let's do it.
