### ISSUE TITLE
Spectral type "Y" missing in 1.6.2

### ISSUE THREAD

**Issue by LukeCEL** [CelestiaProject/CelestiaContent#24]
The nearstars.stc branch uses the spectral type Y for several brown dwarfs, which hasn't been implemented in 1.6.2.

For that, either the code for class "Y" needs to be backported to 1.6.2, or CelestiaContent needs to have a new branch, called "1.6.2" where the class "Y" is replaced with "T9" as a workaround.

**Comment by 375gnu** [comment]
i'd rather backport Y support from 1.7

**Comment by 375gnu** [comment]
fixed in https://github.com/CelestiaProject/Celestia/commit/6e6c5566f33e1a05305d522559bad9ea258224cc
