### ISSUE TITLE
Location of some files

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/CelestiaContent#4]
In recreating my star texture pull request, I notice that some "content" files (such as celestia.cfg) aren't in this repository. So...which files should be here, and which should be in the main repository?

**Comment by 375gnu** [comment]
here - data, extras*, models, textures, all other in the main repo.

**Comment by SevenSpheres** [comment]
As it is I have to make _two_ pull requests to update the star textures, and I'm not sure if I should make those PRs at all yet, since the data files are still in the main repository. I guess the data files will have to be linked like the "thirdparty" stuff is? (That's what the Celestia clone [Cosmonium](https://github.com/cosmonium/cosmonium) does.)

**Comment by 375gnu** [comment]
No, you don't need to make two PRs. Only to this repo. The main one contains data because our build infrastructure for deb & rpm packages is not updated yet.

**Comment by SevenSpheres** [comment]
> No, you don't need to make two PRs.

Yes I do, because celestia.cfg needs to be updated and it's in the main repo.

**Comment by SevenSpheres** [comment]
I guess this is no longer relevant (although content updates requiring `celestia.cfg` changes do still need two PRs)
