### ISSUE TITLE
debian folder and Windows installers

### ISSUE THREAD

**Issue by ajtribick** [CelestiaProject/CelestiaContent#41]
Do the debian folder and the Windows installer files (celestia.iss, win32-installer-image.bmp) belong here, or should these be removed and handled in the main Celestia repository?

**Comment by levinli303** [comment]
I think you are right, we should remove them from this repo.

**Comment by 375gnu** [comment]
debian folder should be kept.

**Comment by ajtribick** [comment]
What's the point of having it in CelestiaContent rather than Celestia?

**Comment by 375gnu** [comment]
To have `celestia-data` as a separate independently managed package.
