### ISSUE TITLE
Unknown stars in asterisms

### ISSUE THREAD

**Issue by ajtribick** [CelestiaProject/CelestiaContent#60]
The asterisms.dat file contains the following stars that do not exist in the datafiles:

* "Star Lac" in Lacerta
* "K Pup" in Puppis
* "Rho Vel" in Vela

None of these designations exists in starnames.dat, and SIMBAD doesn't know them either.

**Comment by SevenSpheres** [comment]
The IAU has [constellation diagrams](https://iau.org/public/themes/constellations/), but only stars with Bayer designations are labeled. Is there another source of diagrams of the commonly used asterisms that labels all stars in the asterism? Celestia Origin does have an alternate version of asterisms.dat, but those asterisms are not in common use.

Might also be worth checking that boundaries.dat is consistent with the IAU constellation boundaries. Looking at the file, I see that there's an "I" or "O" at the end of each line; what do these mean?

**Comment by ajtribick** [comment]
Reading the relevant part of boundaries.cpp, while Celestia reads the "I" and "O" in boundaries.dat (and would stop reading if it isn't there), it doesn't actually do anything with the value. No idea what it originally meant.
