### ISSUE TITLE
New Earth texture has to many artifacts

### ISSUE THREAD

**Issue by 375gnu** [CelestiaProject/CelestiaContent#64]
![image](https://user-images.githubusercontent.com/1612688/147985762-f57fcdad-30ff-4c16-9dcf-0d9caabda12d.png)

**Comment by SevenSpheres** [comment]
This is true. Unfortunately there's no really *good* Earth texture out there, and aside from the "messy" oceans this is probably the best one there is. @Panterstruck is the texture author, we can assign him this issue.

**Comment by TheLostProbe** [comment]
i know that this is an old issue, but why not just make the water a single solid colour? that would get rid of the artifacts, and its the way most people do it with fictional earthlikes afaik

of course, exceptions will have to be made for lakes and coastlines, which are normally more aqua coloured

**Comment by SevenSpheres** [comment]
I should actually post FarGetaNik's cleaned Earth texture here, so someone can scale and add it... https://drive.google.com/drive/folders/1BZAzQbSGrxhj4D-jwf-oYceyURqI8QdC?usp=sharing
