### ISSUE TITLE
Incorrectly positioned atmospheric probe for Galileo and wrong tragectory for it

### ISSUE THREAD

**Issue by SpaceExplorer2008** [CelestiaProject/CelestiaContent#76]
Hi

Today I come to report a bug in Celestia Mobile. There was a recent update that updated textures of planets and moons. In the midst of this, at least one spacecraft was updated: Galileo. This mission consists of an orbiter and an atmospheric probe. The update also added the atmospheric probe. It has its own downloadable addon that adds Galileo. It so happens that with the addon installed, a duplicate of the atmospheric probes was created, as you can see in the images below. One of the duplicates is the original atmospheric probe that even when docked to the Galileo Orbiter is positioned incorrectly and when decoupled from the orbiter it has a bug in its trajectory. The second duplicate is the addon's atmospheric probe. Could you fix this bug? See the screenshot below:
![Screenshot_20220220-203209_Celestia](https://user-images.githubusercontent.com/99847641/154872523-936679f9-a63f-418c-8d33-37af7b423d1e.jpg)

**Comment by 375gnu** [comment]
@SpaceExplorer2008 please provide more information: 1) why do you consider the position is incorrect 2) the same question is for trajectory.

**Comment by SpaceExplorer2008** [comment]
1) Celestia's original atmospheric probe is incorrectly positioned in relation to the orbiter. If you install the addon, you will have a correct placement, but a duplicate will be created.

2) The trajectory of the original atmospheric probe has a fatal bug in its trajectory. After detaching from the orbiter, it simply changes the inclination of its trajectory drastically and ends up disappearing in the orbiter, and the atmospheric probe should impact with the planet Jupiter. Already the addon, the trajectory is correct. 
Screenshot:
![20220221_063603](https://user-images.githubusercontent.com/99847641/154927988-26ded894-c4da-4c08-92c8-f78841548b5d.jpg)

**Comment by SpaceExplorer2008** [comment]
1) Celestia's original atmospheric probe is incorrectly positioned in relation to the orbiter. If you install the addon, you will have a correct placement, but a duplicate will be created.

2) The trajectory of the original atmospheric probe has a fatal bug in its trajectory. After detaching from the orbiter, it simply changes the inclination of its trajectory drastically and ends up disappearing in the orbiter, and the atmospheric probe should impact with the planet Jupiter. Already the addon, the trajectory is correct. 
Screenshot:
![20220221_063805](https://user-images.githubusercontent.com/99847641/154928485-92d7c552-d1d1-432c-86b2-dd20439251f8.jpg)

**Comment by SevenSpheres** [comment]
Is this an issue with the Galileo addon included with default Celestia, or a compatibility issue with the addon on celestia.mobi? If the latter, it should be reported to the addon maintainer @DaveBowman2001.

I'm aware of an issue with the orientation of Huygens in the default content that I don't know how to fix. It's certainly possible that more orientation issues were introduced. It's very difficult to get the orientation of models in Celestia correct.

**Comment by SpaceExplorer2008** [comment]
As the addon was already shipped to Celestia before the update, so I would say it was a problem caused by the update. It was not necessary to update Galileo because it already had an addon that did that.

**Comment by SevenSpheres** [comment]
There's no way to ensure that updates to Celestia's default content don't break any addons. In fact, sometimes making addon-breaking content changes is the only way to keep Celestia's content up to date (for example, making HD 189733 a binary star system). In such cases the addon should be updated for compatibility.

I think you're saying that this issue is only present when the addon is installed, and thus not an issue with default content. If that's the case, it's out of this repository's scope.

**Comment by SpaceExplorer2008** [comment]
I'm not just referring to the addon, I'm also referring to the problem of Celestia's original atmospheric probe, which has a problem with positioning and trajectory with a problem.

**Comment by SpaceExplorer2008** [comment]
I'm not referring to the addon, I'm referring to the original content problem. Don't close this thread, we're not done debating everything yet.

**Comment by SevenSpheres** [comment]
What is the original content problem?

**Comment by SpaceExplorer2008** [comment]
There are two problems with the original content:

1) When the original atmospheric probe is coupled with the orbiter (between 1989 and 1995) the atmospheric probe is misplaced. In the addon there is the right positioning.

2) The trajectory of the atmospheric probe after decoupling from the orbiter, has a problematic trajectory. The inclination of the trajectory changes drastically a few days later and in the end it doesn't end up in Jupiter's atmosphere as it should, and ends up disappearing in the orbiter.

**Comment by SevenSpheres** [comment]
Link to this addon?

**Comment by SpaceExplorer2008** [comment]
https://celestia.space/forum/viewtopic.php?p=154672#p154672

**Comment by SevenSpheres** [comment]
This addon is set up in a very different way to the default version; I'll have to look into it in detail some time... unless @DaveBowman2001 wants to handle this issue?

**Comment by SpaceExplorer2008** [comment]
@SevenSpheres Contact @DaveBowman2001 and describe this issue. Maybe he can modify the addon to fix the original content problem.

**Comment by SevenSpheres** [comment]
We shouldn't be using addons to fix issues with default content; they should be fixed in the default data files. DaveBowman2001 has been pinged multiple times here, I'm sure he'll see this.
