### ISSUE TITLE
Reversed binaries in nearstars.stc

### ISSUE THREAD

**Issue by ajtribick** [CelestiaProject/CelestiaContent#92]
The following is a check on the various binary star systems in the first ~50% of nearstars.stc (down to 36 Oph).

# Reversed orbits
These systems typically look correct from the perspective of the view of the sky-plane, but they are reversed in the radial direction.

## Luhman 16
Reference: https://arxiv.org/pdf/1808.07835.pdf - table 6

In 2014, the radial velocity V_A - V_B is positive, implying that Luhman 16 A is receding faster than Luhman 16 B. In Celestia, this situation is reversed: Luhman 16 A is moving towards the Sun (-ve RV), Luhman 16 B is moving away

## Sirius
Reference: https://arxiv.org/pdf/1809.01240.pdf - figure 9

At the current time, Sirius B should have a positive RV with respect to the system barycenter (i.e. receding). In Celestia, Sirius B is approaching the Sun.

## Gliese 65
Reference: https://www.aanda.org/articles/aa/pdf/2016/09/aa28631-16.pdf - section 3.2

Measured V_B - V_A as positive on 2005-11-17, i.e. Gliese 65 B should be receding w.r.t. Gliese 65 A. In Celestia, Gliese 65 B is approaching the Sun, Gliese 65 A is receding.

## Gliese 234
Reference: https://iopscience.iop.org/article/10.3847/1538-4365/ac7e57/pdf - figure 4

As shown on the RV diagram, the RV of Gliese 234 A at epoch 2456418 should be negative, i.e. approaching. Celestia shows this star as receding.

## Gliese 229
Reference: https://iopscience.iop.org/article/10.3847/1538-3881/ac273e/pdf - figure 8

Radial velocity should be increasing from 2005 to 2020, in Celestia the radial velocity appears to be decreasing.

# Correct orbits
As far as I can see, the following have the correct orbits in terms of radial velocities.

* ALF Cen AB
* Procyon AB
* Gliese 866 AB
* 70 Oph AB
* Gliese 570 BC

# Undetermined
Could not check these, most cases due to insufficient RV data to distinguish between the two possible orientations that match the visual orbit.

* 61 Cyg
* Gliese 866 Aab
* Gliese 725
* Gliese 15
* EPS Ind BC
* SCR 1845-6357
* Gliese 860
* Gliese 473
* GJ 1245
* 40 Eri BC
* GJ 1116
* ETA Cas
* 36 Oph AB

**Comment by JiliTheSpaceboy** [comment]
So I did a little peek into this issue and it looks like Luhman 16's issue is just the erroneous mean anomaly (and for the other parameters, I arrived at slightly different values due to using position in Table 7). I haven't checked the other systems yet at this point.

**Comment by JiliTheSpaceboy** [comment]
Is this one done now?

**Comment by ajtribick** [comment]
I think so for now. Thanks!
