### ISSUE TITLE
Extra star in Eridanus

### ISSUE THREAD

**Issue by 375gnu** [CelestiaProject/CelestiaContent#94]
S Eri

![image](https://user-images.githubusercontent.com/1612688/212555722-693230d5-6a3c-4b87-847f-166f76a89a56.png)

**Comment by ajtribick** [comment]
asterisms.dat specifies that the line goes through the star S Eri = HIP 23231. It should actually go through s Eri = HIP 16754.

**Comment by SevenSpheres** [comment]
See [Celestia#504](https://github.com/CelestiaProject/Celestia/issues/504)
